baseUrl = "https://kefniark.github.io/Fatina/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true
theme = "beautifulhugo"

[Languages]
    [Languages.en]
    title = "Fatina"
    languageName = "English"

    #[Languages.fr]
    #title = "Fatina"
    #languageName = "Francais"

    #[Languages.jp]
    #title = "Fatina"
    #languageName = "日本語"

[Author]
  name = "Kevin Destrem"
  github = "kefniark/fatina"
  twitter = "kefniark"

[params]
  subtitle = "Simple and Fast Tweening library for Typescript/Javascript"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false
  rss = false
  comments = true

  # Prefix URL to edit current page. Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""

  # Description of the site, will be used in meta information
  description = ""

  # Shows a checkmark for visited pages on the menu. Default to false
  showVisitedLinks = false

  # Activate search. Don't forget to generate the JSON index file (go check get started page)
  search = false

  enableLandingPage = true

  landingPageRedirectUrl = "intro"

[[menu.main]]
    name = "Getting Started"
    url = "basics/download/"
    weight = 1

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    url = "samples/generic/"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Basics"
    url = "samples/generic/"
    weight = 1

#[[menu.main]]
#    parent = "samples"
#   name = "DOM / CSS"
#    url = "samples/dom/"
#    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Advanced"
    url = "samples/advanced/"
    weight = 3

[[menu.main]]
    parent = "samples"
    name = "Games"
    url = "samples/game/"
    weight = 4

#[[menu.main]]
#    parent = "samples"
#    name = "three.js"
#    url = "samples/threejs/"
#    weight = 4

[[menu.main]]
    name = "API"
    identifier = "api"
    url = "basics/api/"
    weight = 3

[[menu.main]]
    name = "Fatina"
    parent = "api"
    url = "api/basic/"
    weight = 4

[[menu.main]]
    name = "Tween"
    parent = "api"
    url = "api/tween/"
    weight = 5

[[menu.main]]
    name = "Sequence"
    parent = "api"
    url = "api/sequence/"
    weight = 6

[[menu.main]]
    name = "Benchmark"
    url = "basics/benchmark/"
    weight = 7

[[menu.main]]
    name = "About"
    url = "basics/about/"
    weight = 8